local CB = {
	editorBackground = "#2a324b",
	darkerBackground = "#242b40",
	dark = "#1e2335",
	strings = "#f2c37b",
	warning = "#fcc04f",
	success = "#0ec05c",
	grey_0 = "#b9c0ca",
	light_grey = "#e2e6e9",
	light = "#4f5e8c",
	folder_color = "#eadac3",
	purple = "#B788E5",
	pink = "#ee9cdd",
	red = "#FF738A",
	orange = "#FF955C",
	blue = "#69C3FF",
	cyan = "#22ECDB",
  grey_40 = "#ABB7C1",
  grey_60 = "#262e3d",
  grey_80 = "#303847",
  yellow = "#EACD61"
}

local colors = {
	white = CB.grey_40,
	darker_black = CB.darkerBackground, -- nvim tree (file explorer) background
	black = CB.editorBackground, -- nvim bg
	black2 = CB.editorBackground, -- selection background in Telescope, NVim Tree
	one_bg = CB.grey_60,
	one_bg2 = CB.grey_80, -- StatusBar (filename)
	grey = CB.light, -- Line numbers (shouldn't be base00?)
	grey_fg = "#4e5665", -- Why this affects comments?
	light_grey = "#626a79",
	red = CB.red, -- StatusBar (username)
	pink = CB.pink,
	line = CB.grey_80, -- for lines like vertsplit
	green = CB.success, -- StatusBar (file percentage)
	vibrant_green = "#9bdead",
	blue = CB.blue,
	yellow = CB.yellow,
	sun = "#f6d96d",
	purple = CB.purple,
	orange = CB.orange,
	cyan = CB.cyan,
	statusline_bg = "#232b3a",
	pmenu_bg = "#3CEC85", -- Command bar suggestions
	base00 = CB.editorBackground, -- Default bg
	base01 = CB.grey_60, -- Lighter bg (status bar, line number, folding mks)
	base02 = CB.light, -- Selection bg
	base03 = CB.light, -- Comments, invisibles, line hl
	base04 = "#a1adb7", -- Dark fg (status bars)
	base05 = "#c3cfd9", -- Default fg (caret, delimiters, Operators)
	base06 = CB.grey_40, -- Light fg (not often used)
	base07 = "#08bdba", -- Light bg (not often used)
	base08 = CB.red, -- Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
	base09 = CB.orange, -- Integers, Boolean, Constants, XML Attributes, Markup Link Url
	base0A = CB.yellow, -- Classes, Markup Bold, Search Text Background
	base0B = CB.strings, -- Strings, Inherited Class, Markup Code, Diff Inserted
	base0C = "#77aed7", -- Support, regex, escape chars
	base0D = CB.blue, -- Function, methods, headings
	base0E = CB.cyan, -- Keywords
	base0F = CB.purple, -- Deprecated, open/close embedded tags
}

return colors
